# Generated by Django 4.2.6 on 2023-10-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuNombres', models.CharField(max_length=200)),
                ('usuApellidos', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbUsuarios',
            },
        ),
    ]
